language: c
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3 python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson
script:
  - mkdir build
  - cd build
  - meson ..
  - ninja && ninja test

