language: c
compiler:
  - clang
  - gcc
env: PYENV_VERSION='3.6'
install:
  - sudo apt-get install ninja-build
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --user meson
script:
  - mkdir build
  - cd build
  - meson ..
  - ninja && ninja test

