language: c
python: '3.6'
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install ninja-build
  - pip3 install --user --upgrade pip
  - pip3 install --user meson
script:
  - mkdir build
  - cd build
  - meson ..
  - ninja && ninja test

